# Generated by Django 4.1 on 2024-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_calories_alter_meal_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
